#!/bin/bash -e
# regenerate bookstack secrets and mysql user password

. /etc/default/inithooks

CONF=/var/www/bookstack/.env

DB_USER=bookstack
DB_PASS=$(mcookie)

sed -i "\|^DB_PASSWORD=| s|=.*|=$DB_PASS|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user="$DB_USER" --pass="$DB_PASS"

turnkey-artisan key:generate --force --no-interaction
